#ifndef PLAYER_MOTION_ID_H_
#define PLAYER_MOTION_ID_H_


enum class PlayerMotion_ID
{
	PLAYER_IDEL = 0,
	PLAYER_WALK,
	PLAYER_DESH,
	PLAYER_CLOSE,
	PLAYER_OPEN,
	PLAYER_CLIP,
	PLAYER_CRUSH,
	PLAYER_DAMERGE,
	PLAYER_DEAD,
};
#endif // !PLAYER_MOTION_ID_H_
